theme: jekyll-theme-minimal
title: [Premier League Tipping Competition]
description: [A webpage to host our Premier League Tipping Competition. It should show leaderboards and the Bonus points table and allow tippers to submit their weekly tips]
